parameters:

  # Put the Central Desktop Workspace Template ID here
  cd.workspace_template_hash: WzIxLDQ1OTA2OV0

  # Put the Central Desktop Role ID here
  cd.roles:
    sales_role_hash: WzE1OCwxNzEyXQ
    hdm_pm_role_hash: WzE1OCwyMDkxXQ
    tam_role_hash: WzE1OCwxOTIzXQ
    account_manager_hash: WzE1OCwzNDAwXQ

  # Put the Central Desktop client id and private key here
  auth.cd.client_id: 49c7dbf3-7acf-402f-81de-dffe03025b3b
  auth.cd.private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    
    -----END RSA PRIVATE KEY-----