parameters:
  accountFields:
    - ["ft field", "cd field"]
    - ["ft field", "cd field"]
    - ["ft field", "cd field"]
  workspaceFields:
    - ["ft field", "cd field"]
    - ["ft field", "cd field"]
    - ["ft field", "cd field"]
  milestoneFields:
    - ["ft field", "cd field"]
    - ["ft field", "cd field"]
    - ["ft field", "cd field"]

